(cl:defpackage actionmsg-msg
  (:use )
  (:export
   "<MARKERFEEDBACK>"
   "MARKERFEEDBACK"
   "<MARKERRESULT>"
   "MARKERRESULT"
   "<MARKERGOAL>"
   "MARKERGOAL"
   "<MARKERACTIONFEEDBACK>"
   "MARKERACTIONFEEDBACK"
   "<MARKERACTION>"
   "MARKERACTION"
   "<MARKERACTIONGOAL>"
   "MARKERACTIONGOAL"
   "<MARKERACTIONRESULT>"
   "MARKERACTIONRESULT"
  ))

